replicaCount: 2

image:
  repository: mysql
  tag: "8.0"

secrets:
  MYSQL_ROOT_PASSWORD: "1234"
  MYSQL_USER: "app_user"
  MYSQL_PASSWORD: "1234"

pvc:
  storage: 1Gi

persistence:
  memory: 1Gi
  cpu: 500m

affinity: {}

tolerations: []